### ISSUE TITLE
sql creation and librarys

### ISSUE THREAD

**Issue by braddevans** [matthew-levene/Callout-System#1]
there seems to be some missing library's from your GitHub page like JDBC and JDatePicker
also there are no SQL queries to create the database tables from scratch if the database has been created.

**possible fixes/items:**
1: a copy of the library's inside of a libs folder on the outside of the project
2: a SQL file with the table creation data e.g. create table 'Messages'

**Comment by matthew-levene** [comment]
Hi Brad,

Thank you, I completely forgot about the external libraries -- They've now been added.
 
As the database has already been created and is hosted on a web server, I don't need to create the tables from file, though it is something that I might implement in future projects.
